# Generated by Django 5.1 on 2025-08-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Autur',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
